run:
  concurrency: 12
  deadline: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - darwin
  # skip-dirs:
  skip-files:
    - ".*\\.pb\\.go"
    - ".*(.|_)gen\\.go"
  modules-download-mode: readonly

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    # exclude: .errcheckignore
  goconst:
    min-len: 3
    min-occurrences: 3
  gofmt:
    simplify: true
  goimports:
    local-prefixes: go-darwin.dev/apfs
  golint:
    min-confidence: 0.3
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - dupImport
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  unparam:
    algo: cha
    check-exported: true
  unused:
    check-exported: false

linters:
  enable:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - golint
    - gosec
    - govet
    - lll
    - nakedret
    - scopelint
  fast: true

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - dupl
        - errcheck
        - gocritic

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
